name: Performance Monitoring

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  performance-monitoring:
    name: Daily Performance Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Run performance tests
        run: |
          # Start the application
          npm run serve:local &
          SERVER_PID=$!
          sleep 10

          # Performance monitoring with curl
          echo "=== Performance Metrics ==="
          curl -w "@-" -o /dev/null -s "http://localhost:8080" << 'EOF'
          DNS Lookup:        %{time_namelookup}s
          TCP Connect:       %{time_connect}s
          TLS Handshake:     %{time_appconnect}s
          Server Processing: %{time_starttransfer}s
          Content Transfer:  %{time_total}s
          Total Time:        %{time_total}s
          HTTP Status:       %{http_code}
          Content Size:      %{size_download} bytes
          EOF

          # Memory and bundle analysis
          echo "=== Bundle Analysis ==="
          npm run build:analyze || true

          # Cleanup
          kill $SERVER_PID

      - name: Check performance budgets
        run: |
          echo "=== Performance Budgets ==="
          echo "Checking against performance budgets..."

          # Add performance budget checks here
          # For example, checking bundle size, load time, etc.

          BUNDLE_SIZE=$(du -sh dist/ | cut -f1)
          echo "Bundle size: $BUNDLE_SIZE"

          # Set performance thresholds
          MAX_BUNDLE_SIZE_MB=10

          echo "Performance budget check completed"

      - name: Generate performance report
        run: |
          echo "=== Performance Summary Report ==="
          echo "Date: $(date)"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo ""
          echo "This is a scheduled performance monitoring run."
          echo "Check the logs above for detailed metrics."

  lighthouse:
    name: Lighthouse Performance Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          # Start the application
          npm run serve:local &
          SERVER_PID=$!
          sleep 10

          # Run Lighthouse audit
          lhci autorun --config=lighthouserc.js || true

          # Cleanup
          kill $SERVER_PID